[package]
name = "rustwtxt"
version = "0.1.1"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"
description = "Library that makes working with twtxt.txt files easier."
documentation = "https://docs.rs/rustwtxt"
repository = "https://github.com/gbmor/rustwtxt"
readme = "README.md"
keywords = ["twtxt", "microblogging", "microblog", "tweet"]
categories = ["parsing", "text-processing", "web-programming"]
license = "ISC"
default-run = "rustwtxt"

[badges]
travis-ci = { repository = "gbmor/rustwtxt", branch = "master" }
codecov = { repository = "gbmor/rustwtxt", branch = "master", service = "github" }
maintenance = { status = "experimental" }

[lib]
name = "rustwtxt"
path = "src/lib.rs"

[[bin]]
name = "rustwtxt"
path = "src/bin/main.rs"

[profile.release]
opt-level = 3
lto = true
debug = false
rpath = false
debug-assertions = false
overflow-checks = false

[profile.dev]
opt-level = 0
lto = false
debug = true
rpath = false
debug-assertions = true
overflow-checks = true

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false
rpath = false
overflow-checks = false

[dependencies]
clap = "2.33"
lazy_static = "1.4"
regex = "1"

[dependencies.http_req]
version = "0.5"
default-features=false
features=["rust-tls"]
