[package]
name = "rustwtxt"
version = "0.1.0"
authors = ["Ben Morrison <ben@gbmor.dev>"]
edition = "2018"

[dependencies]
regex = "1"

[dependencies.http_req]
version = "0.5"
default-features=false
features=["rust-tls"]